swagger: '2.0'
info:
  version: '1.0'
  title: "BTEsse3"
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- "http"
- "https"
consumes:
- application/json
produces:
- application/json
paths:
  /users/login:
    post:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"
  /users/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      parameters: []
      responses:
        200:
          description: "OK"
        404:
          description: "User not found"
  /users:
    get:
      tags:
      - "user"
      summary: "Returns all the users"
      description: ""
      operationId: "getUsers"
      responses: 
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
    put:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
            description: "OK"
        400:
          description: "Error while creating user"
    post:
      tags:
      - "user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      parameters:
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "OK"
        404:
          description: "User not found"
  /users/{id}:
    get:
      tags:
      - "user"
      summary: "Returns a user by ID."
      description: ""
      operationId: "getUserById"
      parameters:
      - name: "id"
        in: "path"
        description: "Returns a user by ID."
        required: true
        type: "integer"
      responses: 
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
    delete:
      tags:
      - "user"
      summary: "Delete user by id"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
      parameters:
      - name: "id"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "User not found"
  /userGroups:
    get:
      tags:
      - "userGroup"
      summary: "Return all the users groups"
      description: ""
      operationId: "getUserGroups"
      responses: 
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UserGroup"
        404:
          description: "User group not found"
    post:
      tags:
      - "userGroup"
      summary: "Update user group"
      description: ""
      operationId: "updateUserGroup"
      parameters:
      - in: "body"
        name: "body"
        description: "Updated user group object"
        required: true
        schema:
          $ref: "#/definitions/UserGroup"
      responses:
        200:
          description: "OK"
        404:
          description: "User group not found"
    put:
        tags:
        - "userGroup"
        summary: "Create user group"
        description: ""
        operationId: "createUserGroup"
        parameters:
        - in: "body"
          name: "body"
          description: "Updated user group object"
          required: true
          schema:
            $ref: "#/definitions/UserGroup"
        responses:
          200:
            description: "OK"
          400:
            description: "Error while creating user group"
  /userGroups/{idUserGroup}:
    get:
      tags:
      - "userGroup"
      summary: "Return the user group by id"
      description: ""
      operationId: "getUserGroupById"
      parameters:
      - name: "idUserGroup"
        in: "path"
        required: true
        description: "Return the user group by id"
        type: "integer"
      responses: 
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UserGroup"
        404:
          description: "User group not found"
    delete:
      tags:
      - "userGroup"
      summary: "Delete user group"
      description: ""
      operationId: "deleteUserGroup"
      parameters:
      - name: "idUserGroup"
        in: "path"
        description: "The id that needs to be deleted"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
        404:
          description: "User group not found"
  /tasks:
    post:
      tags:
      - "task"
      summary: "Updated task"
      description: ""
      operationId: "updateTask"
      parameters:
      - in: "body"
        name: "body"
        description: "Updated task object"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Task"
        400:
          description: "Update failed"
    put:
      tags:
      - "task"
      summary: "Create a task"
      description: ""
      operationId: "createTask"
      parameters:
      - in: "body"
        name: "body"
        description: "Created task object"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        200:
          description: "OK"
        400:
          description: "Error while creating task"
  /tasks/{id}:
    get:
      tags:
      - "task"
      summary: "Returns a task by ID."
      description: ""
      operationId: "getTaskId"
      parameters:
      - name: "id"
        in: "path"
        required: true
        description: "ID of the task"
        type: "integer"
      responses: 
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Task"
        400:
          description: "Getting task failed"
        404:
          description: "Task not found"
    delete:
      tags:
      - "task"
      summary: "Delete task"
      description: ""
      operationId: "deleteTask"
      parameters:
      - name: "id"
        in: "path"
        description: "The id that needs to be deleted"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
        404:
          description: "Task not found"
  /tasks/{idTask}/review:
    get:
      tags:
      - "task"
      summary: "Get the review of a tasks by id"
      description: ""
      operationId: "getReviewsByIdTask"
      parameters:
      - name: "idTask"
        in: "path"
        description: "The id of the task"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Review"
        400:
          description: "Getting reviews failed"
        404:
          description: "Review not found"
  /tasks/review:
    post:
      tags:
      - "task"
      summary: "Review a task"
      description: ""
      operationId: "reviewTaskById"
      parameters:
      - in: "body"
        name: "body"
        description: "Rewiew task object"
        required: true
        schema:
          $ref: "#/definitions/Review"
      responses:
        200:
          description: "OK"
        400:
          description: "Review failed"
  /tasks/reviews/evaluate:
    post:
      tags:
      - "task"
      summary: "Evaluate the review of the task"
      description: ""
      operationId: "evaluateReviewTaskById"
      parameters:
      - in: "body"
        name: "body"
        description: "Evaluate rewiew task object"
        required: true
        schema:
          $ref: "#/definitions/Review"
      responses:
        200:
          description: "OK"
        400:
          description: "Evaluation of the review failed"
  /exams/idUsers/{idUser}:
    get:
      tags:
      - "exam"
      summary: "Return the exams created by user"
      description: ""
      operationId: "getExams"
      parameters:
      - name: "idUser"
        in: "path"
        required: true
        description: "Return the exams created by user"
        type: "integer"
      responses: 
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Exam"
        404:
          description: "Exam not found"
  /exams:
    post:
      tags:
      - "exam"
      summary: "Update the exam"
      description: ""
      operationId: "updateExam"
      parameters:
      - in: "body"
        name: "body"
        description: "Created exam object"
        required: true
        schema:
          $ref: "#/definitions/Exam"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Exam"
        400:
          description: "Update failed"
    put:
      tags:
      - "exam"
      summary: "Create an exam"
      description: ""
      operationId: "createExam"
      parameters:
      - in: "body"
        name: "body"
        description: "Created exam object"
        required: true
        schema:
          $ref: "#/definitions/Exam"
      responses:
        200:
          description: "OK"
        400:
          description: "Exam creation failed"
  /exams/{idExam}:
    get:
      tags:
      - "exam"
      summary: "Return the exam by id"
      description: ""
      operationId: "getExamById"
      parameters:
      - name: "idExam"
        in: "path"
        required: true
        description: "Return the exam by id"
        type: "integer"
      responses: 
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Exam"
        404:
          description: "Exam not found"
    delete:
      tags:
      - "exam"
      summary: "Delete exam"
      description: ""
      operationId: "deleteExam"
      parameters:
      - name: "idExam"
        in: "path"
        description: "The id that needs to be deleted"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
        404:
          description: "Exam not found"
  /sessionExams:
    get:
      tags:
      - "sessionExam"
      summary: "Return all the exams of a sessions"
      description: ""
      operationId: "getSessionsExams"
      responses: 
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/SessionExam"
        404:
          description: "Exam session not found"
    post:
      tags:
      - "sessionExam"
      summary: "Update exam session"
      description: ""
      operationId: "updateSessionExam"
      parameters:
      - in: "body"
        name: "body"
        description: "Updated exam session object"
        required: true
        schema:
          $ref: "#/definitions/SessionExam"
      responses:
        200:
          description: "OK"
        404:
          description: "Exam session not found"
    put:
        tags:
        - "sessionExam"
        summary: "Create a exam session"
        description: ""
        operationId: "createSessionExam"
        parameters:
        - in: "body"
          name: "body"
          description: "Create exam session object"
          required: true
          schema:
            $ref: "#/definitions/SessionExam"
        responses:
          200:
            description: "OK"
          400:
            description: "Error while creating exam session"
  /sessionExams/{idSession}:
    get:
      tags:
      - "sessionExam"
      summary: "Return the exams of a session by id"
      description: ""
      operationId: "getSessionExamById"
      parameters:
      - name: "idSession"
        in: "path"
        required: true
        description: "Return the exams of a session by id"
        type: "integer"
      responses: 
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/SessionExam"
        404:
          description: "Exam session not found"
    delete:
      tags:
      - "sessionExam"
      summary: "Delete a exam session"
      description: ""
      operationId: "deleteSessionExam"
      parameters:
      - name: "idSession"
        in: "path"
        description: "The id that needs to be deleted"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
        404:
          description: "Exam session not found"
  /submissions:
    post:
      tags:
      - "submission"
      summary: "Submit exam"
      description: ""
      operationId: "submitExam"
      parameters:
      - in: "body"
        name: "body"
        description: "Submitted exam object"
        required: true
        schema:
          $ref: "#/definitions/Submission"
      responses:
        200:
          description: "OK"
        400:
          description: "Submission not well formed"
definitions:
  User:
    type: "object"
    required:
    - "id"
    - "username"
    - "email"
    - "password"
    properties:
      id:
        type: "integer"
        format: "int64"
        minimum: 1
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
    xml:
      name: "User"
  UserGroup:
    type: "object"
    required:
    - "id"
    - "users"
    properties:
      id:
        type: "integer"
        format: "int64"
      users:
        type: "array"
        xml:
          name: "users"
          wrapped: true
        items:
          $ref: "#/definitions/User"
    xml:
      name: "UserGroup"
  Task:
    type: "object"
    required:
    - "id"
    - "type"
    - "request"
    - "response"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        type: "string"
      request:
        type: "string"
      response:
        type: "string"
      reviews:
        type: "array"
        xml:
          name: "tasks"
          wrapped: true
        items:
          $ref: "#/definitions/Review"
    xml:
      name: "Task"
  Exam:
    type: "object"
    required:
    - "nameExam"
    - "idExam"
    - "valutation"
    - "tasks"
    properties:
      nameExam:
        type: "string"
      idExam:
        type: "integer"
        format: "int64"
      idUser:
        type: "integer"
        format: "int64"
      valutation:
        type: "integer"
        format: "int64"
      tasks:
        type: "array"
        xml:
          name: "exams"
          wrapped: true
        items:
          $ref: "#/definitions/Task"
    xml:
      name: "TaskGroup"
  SessionExam:
    type: "object"
    required:
    - "id"
    - "exams"
    properties:
      id:
        type: "integer"
        format: "int64"
      exams:
        type: "array"
        xml:
          name: "exams"
          wrapped: true
        items:
          $ref: "#/definitions/Exam"
    xml:
      name: "SessionExam"
  Submission:
    type: "object"
    required:
    - "id"
    - "idUser"
    - "exam"
    properties:
      id:
        type: "integer"
        format: "int64"
      idUser:
        type: "integer"
        format: "int64"
      exam:
        $ref: "#/definitions/Exam"
    xml:
      name: "Submission"
  Review:
    type: "object"
    required:
    - "idReview"
    - "idUser"
    - "idTask"
    - "message"
    properties:
      idReview:
        type: "integer"
        format: "int64"
      idUser:
        type: "integer"
      idTask:
        type: "integer"
      message:
        type: "string"
      mark:
        type: "integer"
    xml:
      name: "Review"
